### ISSUE TITLE
Address incentives for transcoding candidates

### ISSUE THREAD

**Issue by dob** [livepeer/wiki#6]
The protocol needs to better delineate the incentives for nodes to delegate bonded stake towards candidate transcoders. Options we're considering include:

- transitive delegation
- a newly minted token stake for candidate delegated stake (no fee exposure but no slashing risk)
- random candidate participation in rounds

**Comment by yondonfu** [comment]
Some additional things to consider:

- The size of the candidate transcoder set. 1 vs. `N`? How many transcoders would sit around in the hopes of joining the active transcoder pool? Transitive delegation seems like a possible solution to attracting delegated stake to incentivize nodes to be candidate transcoders here.
- What happens when the set of candidate transcoders is full? Do we just have a fixed set of candidate transcoders until one drops out and then a node who wants to become a transcoder can join the candidate set?

**Comment by dob** [comment]
I think a cap on the # of candidates in the pool is reasonable. A candidate
should have to pass the bar of either putting up enough of their own stake,
or convincing enough delegates of their candidacy or they're unlikely to
have the resources/hardware/bandwidth/expertise to be an effective active
transcoder anyway. Whether that number is `N` or something else, is TBD.

**Comment by dob** [comment]
Addressed via streamflow.
